app:
  build: .
  volumes:
    - .:/my_phoenix
  working_dir: /my_phoenix
  command: 'scripts/container/startup.sh'
  ports:
    - '4000:4000'
  links:
    - db
db:
  image: postgres:9.4
  environment:
    POSTGRES_USER: 'phoenix_blog'
  ports:
    - '5432'
  volumes:
    - ./backup:/backup

backup:
  image: Dockerfile-backup
  volumes:
    - ./backup:/backup
  environment:
    POSTGRES_USER: 'phoenix_blog'
  links:
    - db
