app:
  build: .
  environment:
    MIX_ENV=test
  volumes:
    - .:/my_phoenix
  working_dir: /my_phoenix
  command: 'scripts/container/startup_development.sh'
  ports:
    - '4000:4000'
  links:
    - db
db:
  image: postgres:9.4
  environment:
    POSTGRES_USER: 'phoenix_blog'
  ports:
    - '5432'

